[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PPDRS"
version = "0.1.0"
dependencies = [
    "pycryptodome",
    "threshold-crypto @ git+https://github.com/tompetersen/threshold-crypto.git"
]
